version: '3.3'

services:
  workspace:
    container_name: real-estate-workspace
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3250:3250"
    tty: true
    volumes:
      - ..:/workspaces/real-estate:cached
      - ./real-estate.local.conf:/etc/nginx/conf.d/real-estate.local.conf
      - ./xdebug.ini:/etc/php/7.2/mods-available/xdebug.ini
    command: sleep infinity
  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379

