version: '3.3'

services:
  workspace:
    container_name: real-estate-workspace
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3250:3250"
    volumes:
      - ..:/workspaces/real-estate
      - ./real-estate.local.conf:/etc/nginx/conf.d/real-estate.local.conf
    command: sleep infinity
